@peachtree_bank_poc_HostAddress = https://localhost:7080
@token = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjMwYjIyMWFiNjU2MTdiY2Y4N2VlMGY4NDYyZjc0ZTM2NTIyY2EyZTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcGVhY2h0cmVlLWJhbmstYjNlZGQiLCJhdWQiOiJwZWFjaHRyZWUtYmFuay1iM2VkZCIsImF1dGhfdGltZSI6MTc0MjgwMDk3NCwidXNlcl9pZCI6IjdmTGl3QTdmQ0JoOG0xY3dDZ3dqd0tOUE1ERDIiLCJzdWIiOiI3Zkxpd0E3ZkNCaDhtMWN3Q2d3andLTlBNREQyIiwiaWF0IjoxNzQyODQyNzM2LCJleHAiOjE3NDI4NDYzMzYsImVtYWlsIjoiYWxlay5seW5nZUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiYWxlay5seW5nZUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.cwdcT2r7g2vrBFSEy8Ikw9YjgDhgPuWlPG6lEzhy9LqgaIWr6t1i4R-zvkU-4HDue46m06G4eBl6iI_f_yrWy3zs-cETOQx_GWrlRW9UQPhWouhrw2XGuQRAgmJ-w-2s8DIRgu14d8_AA3uwZyGUepjJ9Z2stxcLD89pwdfeJQGvs-BxweBORqE6dqr6FwZ36T5Fci7csQiiqkn8KFCiJoVoygCkRyEv4iiRwghV0xNq6s1RP5CydsDueX3zgYd1FhX2XQoRS8b6jPVWK3ct2VS4CED3RG9kRycNs3GpXKIxFqw5LyrEJCPfnJfIytQ__GzZaBr6dA_je3boGZRqzA"
GET {{peachtree_bank_poc_HostAddress}}/api/transactions/0195c482-19a5-7fd2-86a6-c6623355d4fd
Accept: application/json
Authorization: Bearer {{token}}
### Freetext search and sorting
GET {{peachtree_bank_poc_HostAddress}}/api/transactions/-10/10/?sortBy=Amount&sortDirection=asc
Accept: application/json


### Create Transaction
POST {{peachtree_bank_poc_HostAddress}}/api/transactions
Content-Type: application/json

{
  "fromAccount": "Desiro Industries",
  "toAccount": "Flatline Hikers",
  "amount": 1001.11
}

### Update Transaction State
PUT {{peachtree_bank_poc_HostAddress}}/api/transactions/0195c47b-c7aa-76e7-a2bc-4cc840661cbd/state/2
Accept: application/json


### Bulk Create Transactions
POST {{peachtree_bank_poc_HostAddress}}/api/transactions/bulk
Content-Type: application/json

[
  {
    "fromAccount": "GlobeTech",
    "toAccount": "MegaMart",
    "amount": 1234.56
  },
  {
    "fromAccount": "ApexTraders",
    "toAccount": "MarketDepot",
    "amount": -500.25
  },
  {
    "fromAccount": "BrightEnterprises",
    "toAccount": "UrbanCo",
    "amount": 78.0
  },
  {
    "fromAccount": "NorthernSupplies",
    "toAccount": "SilverExchange",
    "amount": 99999.99
  },
  {
    "fromAccount": "MidasCorp",
    "toAccount": "GreenGrocer",
    "amount": -200.45
  },
  {
    "fromAccount": "UnityBanks",
    "toAccount": "TitanConstruction",
    "amount": 3000.0
  },
  {
    "fromAccount": "SolarDynamics",
    "toAccount": "OmniFoods",
    "amount": -42.5
  },
  {
    "fromAccount": "AtlasShipping",
    "toAccount": "QuantumRetail",
    "amount": 48.72
  },
  {
    "fromAccount": "SkylineLogistics",
    "toAccount": "TransGlobal",
    "amount": 10000.0
  },
  {
    "fromAccount": "EverestChemicals",
    "toAccount": "FusionDeli",
    "amount": -1234.99
  },
  {
    "fromAccount": "BlueOcean",
    "toAccount": "ZenithStores",
    "amount": 150.75
  },
  {
    "fromAccount": "TerraExports",
    "toAccount": "EcoVision",
    "amount": 12.34
  },
  {
    "fromAccount": "RedStone",
    "toAccount": "ClearBridge",
    "amount": -100.0
  },
  {
    "fromAccount": "CyberLink",
    "toAccount": "TechMatrix",
    "amount": 2450.0
  },
  {
    "fromAccount": "PhotonicsCorp",
    "toAccount": "NovaMarkets",
    "amount": -123.456
  },
  {
    "fromAccount": "EchoMarine",
    "toAccount": "RiverTrade",
    "amount": 999.99
  },
  {
    "fromAccount": "FuturaFinance",
    "toAccount": "AstraFood",
    "amount": -450.0
  },
  {
    "fromAccount": "PrimeMotion",
    "toAccount": "MidlandSupplies",
    "amount": 1.5
  }
]
